routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.index');
})->middleware('guest');

Route::get('/dashboard', 'AdminController@dashboard');
Route::post('/updateprofile/{id}', 'AdminController@updateprofile');
Route::get('/ProfileSetting/{ids?}', 'AdminController@ProfileSetting');
Route::post('/changepassword/{id}', 'AdminController@changepassword');
Route::post('/onchangestatus/{id}', 'AdminController@onchangestatus');
Route::get('/Users', 'AdminController@Users');
Route::post('/useronchangestatus/{id}', 'AdminController@useronchangestatus');
Route::get('/editusers/{id}', 'AdminController@updateusers');
Route::post('/updateuser/{id}', 'AdminController@updateuser');
Route::get('/addusers', 'AdminController@addusers');
Route::post('/adduser', 'AdminController@adduser');
Route::get('/Registerconfirmation/{id}', 'AdminController@Registerconfirmation');
Route::group(['prefix' => 'user'], function() {
    Route::post('/searchdetails', 'AdminController@searchdetails');
    Route::get('/submit', 'AdminController@submitlist');
    Route::get('/submit/{type?}/{db?}', 'AdminController@submitaction')->name('submit.action');
});
Route::get('/user/Activation/{token}', 'HomeController@Activation');
Route::get('/test/{cc}', 'HomeController@test');

Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {
    Route::resource('news','NewsController');
    Route::resource('category','CategoryController');
    Route::get('ProductList', 'AdminController@ProductList')->name('product.list');
    Route::post('searchproduct', 'AdminController@searchproduct');
    Route::get('SearchProductList', 'AdminController@SearchProductList');
    Route::get('editproduct/{id}', 'AdminController@editproduct');
    Route::post('updateproduct/{id}', 'AdminController@updateproduct');
    Route::get('backup', 'AdminController@backup');
    Route::post('generate', 'AdminController@generateBackup')->name('admin.backup.generate');
    Route::post('process', 'AdminController@processBackupFile')->name('admin.backup.process');
    Route::get('AddCsv', 'AdminController@AddCsv');
    Route::post('uploadcsv', 'AdminController@uploadcsv');
    Route::post('excel/{action}/{type}', 'AdminController@excel')->name('admin.excel');
    Route::get('filter', 'AdminController@getFilter')->name('admin.filter');
    
});

Auth::routes([
    'register' => false, 
    'reset' => false
  ]);
Route::get('lang/{lang}', 'AdminController@changeLang');
//Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name', 'slug', 'image', 'status'];

    
    public function newslist()
    {
        return $this->hasMany('App\News');
    }
}

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = ['title', 'slug', 'details', 'image','video','category_id', 'status', 'featured', 'view_count'];

    
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{

    public function index()
    {   
        //return 'index cat';
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Category';
        $data['categories'] = Category::latest()->get();
        return view('admin.news.category.index', $data);
    }


    public function create()
    {
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Category';
        return view('admin.news.category.create',$data);
    }


    public function store(Request $request)
    {
        $request->validate([
            'name'   => 'required|unique:categories|max:255',
            // 'image'  => 'required|image|mimes:jpg,png,jpeg'
        ]);

        if ($request->hasFile('image')) {
            $imageName = 'category-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);
        }else{
            $imageName = 'default-category.png';
        }

        Category::create([
            'name'   => $request->name,
            'slug'   => str_slug($request->name),
            'image'  => $imageName,
            'status' => true
        ]);
        return redirect()->route('category.index')->with(['message' => 'Category created successfully!']);
    }


    public function show(Category $category)
    {
        //
    }

    
    public function edit(Category $category)
    {
        $category = Category::findOrFail($category->id);
        return view('admin.news.category.edit', compact('category'));
    }


    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name'   => 'required|max:255',
            'image'  => 'image|mimes:jpg,png,jpeg'
        ]);
        $status = true;
        $category = Category::findOrFail($category->id);

        if ($request->hasFile('image')) {

            if(file_exists(public_path('img/news/') . $category->image)){
                unlink(public_path('img/news/') . $category->image);
            }
            $imageName = 'category-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);

        }else{
            $imageName = $category->image;
        }

        $category->update([
            'name'   => $request->name,
            'slug'   => str_slug($request->name),
            'image'  => $imageName,
            'status' => $status
        ]);

        return redirect()->route('category.index')->with(['message' => 'Category updated successfully!']);
    }


    public function destroy(Category $category)
    {
        $category = Category::findOrFail($category->id);

        if(file_exists(public_path('img/news/') . $category->image)){
            unlink(public_path('img/news/') . $category->image);
        }

        $category->delete();

        return back()->with(['message' => 'Category deleted successfully!']);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use App\Category;
use Illuminate\Http\Request;
use VideoThumbnail;

class NewsController extends Controller
{

    public function index()
    {
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Articles';
        $data['newslist'] = News::with('category')->latest()->get();
        return view('admin.news.index', $data);
    }


    public function create()
    {
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Articles';
        $data['categories'] = Category::latest()->select('id','name')->where('status',1)->get();
        return view('admin.news.create', $data);
    }


    public function store(Request $request)
    {
        $request->validate([
            'title'         => 'required|unique:news|max:255',
            'details'       => 'required',
            'image'         => 'image|mimes:jpg,png,jpeg',
            'video'         => 'mimes:mp4,mov,ogg,webm|max:100000',
        ]);
    
        $status = true; //publish
        $featured = true; //on
        $imageName = 'no-thumbnail-post.jpg';
        $videoThumb = 'no-video.png';
        if ($request->hasFile('image')) {
            $imageName = 'news-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);
        }
        if ($request->hasFile('video')) {
            $video = 'video-'.time().uniqid().'.'.$request->video->getClientOriginalExtension();
            $request->video->move(public_path('img/news/video'), $video);
            $thumbnail_path= public_path('img/news/vthumbs');
            $videoUrl  = public_path('img/news/video/').$video;
            //$video_path       = $destination_path.'/'.$file_name;
            $thumbnail_image  = $video.".jpg";
            $thumbnail_status = VideoThumbnail::createThumbnail($videoUrl,$thumbnail_path,$thumbnail_image,2,$width = 640, $height = 480);
            //VideoThumbnail::createThumbnail($videoUrl, $storageUrl, $fileName, $second, $width = 640, $height = 480);
            //$abc = VideoThumbnail::createThumbnail(public_path('img/news/'), public_path('files/thumbs/'), 'movie.jpg', 2, 1920, 1080);
            if($thumbnail_status)
            {
                $videoThumb = $thumbnail_image;
              
            }
          
        }
            News::create([
                'title'         => $request->title,
                'slug'          => str_slug($request->title),
                'details'       => $request->details,
                'category_id'   => $request->category_id ?? 1,
                'image'         => $imageName,
                'video'         => $videoThumb,
                'status'        => $status,
                'featured'      => $featured
            ]);
    
        return redirect()->route('news.index')->with(['message' => 'News created successfully!']);
    }


    public function show(News $news)
    {
        //
    }


    public function edit(News $news)
    {   
        $data['menu'] = __('menu.Edit News');
        $data['sub_menu'] = 'Articles';
        $data['categories'] = Category::latest()->select('id','name')->where('status',1)->get();
        $data['news'] = News::findOrFail($news->id);     
        return view('admin.news.edit', $data);
    }

 
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title'         => 'required|max:255',
            'details'       => 'required',
            'image'         => 'image|mimes:jpg,png,jpeg',
            'video'         => 'mimes:mp4,mov,ogg,webm|max:100000',
        ]);
        $status = true; //publish
        $featured = true; //on    
        $news = News::findOrFail($news->id);

        if ($request->hasFile('image')) {
            if(file_exists(public_path('img/news') . $news->image)){
                unlink(public_path('img/news') . $news->image);
            }

            $imageName = 'news-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);

        }else{
            $imageName = $news->image;
        }

        if ($request->hasFile('video')) {
            if(file_exists(public_path('img/news/video') . $news->video)){
                unlink(public_path('img/news/video') . $news->video);
            }

            $video = 'news-'.time().uniqid().'.'.$request->video->getClientOriginalExtension();
            $request->video->move(public_path('img/news/video'), $video);
            $thumbnail_path= public_path('img/news/vthumbs');
            $videoUrl  = public_path('img/news/video/').$video;

            $thumbnail_image  = $video.".jpg";
            $thumbnail_status = VideoThumbnail::createThumbnail($videoUrl,$thumbnail_path,$thumbnail_image,2,$width = 640, $height = 480);
        
            if($thumbnail_status)
            {
                $videoThumb = $thumbnail_image;
              
            }

        }else{
            $videoThumb = $news->video;
        }

        $news->update([
            'title'         => $request->title,
            'slug'          => str_slug($request->title),
            'details'       => $request->details,
            'category_id'   => $request->category_id ?? 1,
            'image'         => $imageName ?? 'no-thumbnail-post.jpg',
            'video'         => $videoThumb ?? 'no-video.png',
            'status'        => $status,
            'featured'      => $featured
        ]);

        return redirect()->route('news.index')->with(['message' => 'News updated successfully!']);
    }

 
    public function destroy(News $news)
    {
        $news = News::findOrFail($news->id);
        if($news->image !='no-thumbnail-post.jpg'){
            if(file_exists(public_path('img/news/') . $news->image)){
                unlink(public_path('img/news/') . $news->image);
            }
        }
        if($news->video !='no-video.png'){
            if(file_exists(public_path('img/news/vthumbs/') . $news->video)){
                unlink(public_path('img/news/vthumbs/') . $news->video);
            }
        }
        $videoname = str_replace('.jpg','',$news->video);
        if(file_exists(public_path('img/news/video/') . $videoname)){
            unlink(public_path('img/news/video/') . $videoname);
        }
        $news->delete();

        return back()->with(['message' => 'News deleted successfully!']);
    }
}

resources/views/admin/news/category/create.blade.php
@extends('layout.master')
@section('css')
@endsection
@section('content')
<section id="main-content">
          <section class="wrapper">
<!-- page start-->
<div class="row">
<div class="col-sm-12 overflow-auto">
<section class="card">

<header class="card-header">
{{ __('menu.Create Category') }}
<span class="tools pull-right">
<a href="javascript:;" class="fa fa-chevron-down"></a>
<a href="javascript:;" class="fa fa-times"></a>
</span>
</header>
<!-- card body -->
<div class="card-body">
</div>
<!-- end card body -->
<!-- card table -->
<div class="card-body overflow-auto">
<form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data" role="form">
    @csrf
<div class="row">
    <div class="col-md-6">
        <div class="box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Create Category</h3>
            </div>

            <div class="box-body">
                <div class="form-group">
                    <label for="categoryname">Category Name</label>
                    <input type="text" name="name" class="form-control" id="categoryname">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Category Image</h3>
            </div>
            <div class="box-body">
                <div class="form-group">
                    <input type="file" name="image" id="categoryimage">
                    <p class="help-block">(Image must be in .png or .jpg format)</p>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="status"> Active
                    </label>
                </div>
            </div>

            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Submit</button>
            </div>
        </div>
    </div>
</div>
</form>
</div>
<!-- end card table -->
</section>
</div>
</div>
<!-- page end-->
    </section>
</section>
<!--main content end-->
@endsection
@section('css')
@endsection

resources/views/admin/news/category/edit.blade.php
@if(isset($category))
<form action="{{ route('category.update',[$category->id]) }}" method="POST" enctype="multipart/form-data" role="form">
                @csrf
                @method('PUT')
            <div class="modal-body">
                <div class="form-group">
                    <label for="name">{{__('form.Category Name')}}</label>
                    <input id="name" class="form-control" type="text" name="name" value="{{$category->name}}">
                </div>
                <div class="form-group">
                    <label for="image">{{__('form.Image')}}</label>
                    <div style="width:50%;margin:0 auto;padding:10px;">
                    <img class="img-thumbnail" src="{{ asset('img/news/'.$category->image) }}" alt="{{ $category->name }}">
                    </div>
                    <input id="image" class="form-control-file" type="file" name="image">
                </div>
               
            </div>
            <div class="modal-footer">
                <div class="btn-group" role="group" aria-label="Button group">
                    <button class="btn btn-primary" type="submit">{{__('form.action.Save')}}</button>
                </div>
            </div>
            </form>
@endif            

resources/views/admin/news/category/index.blade.php
@extends('layout.master')
@section('css')
@endsection
@section('content')
<section id="main-content">
          <section class="wrapper">
<!-- page start-->
<div class="row">
<div class="col-sm-12 overflow-auto">
<section class="card">

<header class="card-header">
    {{ __('menu.category') }}
<span class="tools pull-right">
<button type="button" class="btn btn-danger" onclick="openCat()" > <i class="fa fa-pencil"></i>&nbsp;{{ __('table.action.create') }}</button>

@include('forms.form-modal', ['title'=>__('form.Edit Category')])
<a href="javascript:;" class="fa fa-chevron-down"></a>
<a href="javascript:;" class="fa fa-times"></a>
</span>
<div id="addcategory" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="my-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="my-modal-title">{{__('form.Add Category')}}</h5>
                <button class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('category.store') }}" method="POST" enctype="multipart/form-data" role="form">
                @csrf
            <div class="modal-body">
                <div class="form-group">
                    <label for="name">{{__('form.Category Name')}}</label>
                    <input id="name" class="form-control" type="text" name="name">
                </div>
                <div class="form-group">
                    <label for="image">{{__('form.Image')}}</label>
                    <input id="image" class="form-control-file" type="file" name="image">
                </div>
               
            </div>
            <div class="modal-footer">
          
                <div class="btn-group" role="group" aria-label="Button group">
                    <button class="btn btn-primary" type="submit">{{__('form.action.Save')}}</button>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
</header>
<!-- card body -->
<div class="card-body">
</div>
<!-- end card body -->
<!-- card table -->
<div class="card-body overflow-auto">
    <div class="adv-table">
    <table class="display table table-bordered table-striped" style="width:100%" id="tcat">
                            <thead>
                                <tr>
                                    <th>{{ __('table.ID') }}</th>
                                    <th>{{ __('table.Image') }}</th>
                                    <th>{{ __('table.name') }}</th>
                                    <th>{{ __('table.Slug') }}</th>
                                    <th>{{ __('table.Status') }}</th>
                                    <th>{{ __('table.action.action') }}</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach($categories as $category)
                                <tr class="gradeX">
                                    <td>{{ $category->id }}</td>
                                    <td>
                                        <img src="{{ asset('img/news/'.$category->image) }}" alt="{{ $category->name }}" width="40px">
                                    </td>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ $category->slug }}</td>
                                    <td>{{ $category->status ? 'Active' : 'Inactive' }}</td>
                                    <td>
                                        <div class="btn-group-horisontal text-center">
                                        <a class="btn btn-warning btn-flat load-form-modal" data-url="{{ route('category.edit',[$category->id]) }}" data-toggle ="modal" data-target='#form-modal' href="#"><i class="fa fa-edit"></i></a>
                                            
                                            <a href="javascript:void(0)" class="btn btn-danger btn-flat"
                                                onclick="event.preventDefault();
                                                        document.getElementById('category-delete-form-{{$category->id}}').submit();">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <form id="category-delete-form-{{$category->id}}" action="{{ route('category.destroy',$category->id) }}" method="POST" style="display: none;">
                                                @csrf 
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                            <tfoot>
                                <tr>
                                <th>{{ __('table.ID') }}</th>
                                    <th>{{ __('table.Image') }}</th>
                                    <th>{{ __('table.name') }}</th>
                                    <th>{{ __('table.Slug') }}</th>
                                    <th>{{ __('table.Status') }}</th>
                                    <th>{{ __('table.action.action') }}</th>
                                </tr>
                            </tfoot>
                        </table>
    </div>
</div>
<!-- end card table -->
</section>
</div>
</div>
<!-- page end-->
    </section>
</section>
<!--main content end-->
@endsection
@section('js')
<script>
 var oUsers = $('#tcat').dataTable({
        "order": [[0,"asc"]],
        "columnDefs": [{
        "targets"  : 'no-sort',
        "orderable": false,
        },
        { "width": "5%", "targets": 0 }],
        "pageLength": 25,
    });
function openCat(){
    $('#addcategory').modal('show');
}
var Modal = {
    init: function () {
        this.initEditModal();
        
    },
    initEditModal: function() {
        $(document).on('click', '.load-form-modal', function(event){
            console.log('Modal: '+ $(this).attr('data-url'));
            $('#form-modal .isi').load($(this).attr('data-url'));
            event.preventDefault();
        });
    },
};

Modal.init();
</script>
@endsection