routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.index');
})->middleware('guest');

Route::get('/dashboard', 'AdminController@dashboard');
Route::post('/updateprofile/{id}', 'AdminController@updateprofile');
Route::get('/ProfileSetting/{ids?}', 'AdminController@ProfileSetting');
Route::post('/changepassword/{id}', 'AdminController@changepassword');
Route::post('/onchangestatus/{id}', 'AdminController@onchangestatus');
Route::get('/Users', 'AdminController@Users');
Route::post('/useronchangestatus/{id}', 'AdminController@useronchangestatus');
Route::get('/editusers/{id}', 'AdminController@updateusers');
Route::post('/updateuser/{id}', 'AdminController@updateuser');
Route::get('/addusers', 'AdminController@addusers');
Route::post('/adduser', 'AdminController@adduser');
Route::get('/Registerconfirmation/{id}', 'AdminController@Registerconfirmation');
Route::group(['prefix' => 'user'], function() {
    Route::post('/searchdetails', 'AdminController@searchdetails');
    Route::get('/submit', 'AdminController@submitlist');
    Route::get('/submit/{type?}/{db?}', 'AdminController@submitaction')->name('submit.action');
});
Route::get('/user/Activation/{token}', 'HomeController@Activation');
Route::get('/test/{cc}', 'HomeController@test');

Route::group(['prefix' => 'admin', 'middleware' => 'role:admin'], function() {
    Route::resource('news','NewsController');
    Route::resource('category','CategoryController');
    Route::get('ProductList', 'AdminController@ProductList')->name('product.list');
    Route::post('searchproduct', 'AdminController@searchproduct');
    Route::get('SearchProductList', 'AdminController@SearchProductList');
    Route::get('editproduct/{id}', 'AdminController@editproduct');
    Route::post('updateproduct/{id}', 'AdminController@updateproduct');
    Route::get('backup', 'AdminController@backup');
    Route::post('generate', 'AdminController@generateBackup')->name('admin.backup.generate');
    Route::post('process', 'AdminController@processBackupFile')->name('admin.backup.process');
    Route::get('AddCsv', 'AdminController@AddCsv');
    Route::post('uploadcsv', 'AdminController@uploadcsv');
    Route::post('excel/{action}/{type}', 'AdminController@excel')->name('admin.excel');
    Route::get('filter', 'AdminController@getFilter')->name('admin.filter');
    
});

Auth::routes([
    'register' => false, 
    'reset' => false
  ]);
Route::get('lang/{lang}', 'AdminController@changeLang');
//Route::get('/home', 'HomeController@index')->name('home');

app/News.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $fillable = ['title', 'slug', 'details', 'image','video','category_id', 'status', 'featured', 'view_count'];

    
    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\News;
use App\Category;
use Illuminate\Http\Request;
use VideoThumbnail;

class NewsController extends Controller
{

    public function index()
    {
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Articles';
        $data['newslist'] = News::with('category')->latest()->get();
        return view('admin.news.index', $data);
    }


    public function create()
    {
        $data['menu'] = __('menu.news');
        $data['sub_menu'] = 'Articles';
        $data['categories'] = Category::latest()->select('id','name')->where('status',1)->get();
        return view('admin.news.create', $data);
    }


    public function store(Request $request)
    {
        $request->validate([
            'title'         => 'required|unique:news|max:255',
            'details'       => 'required',
            'image'         => 'image|mimes:jpg,png,jpeg',
            'video'         => 'mimes:mp4,mov,ogg,webm|max:100000',
        ]);
    
        $status = true; //publish
        $featured = true; //on
        $imageName = 'no-thumbnail-post.jpg';
        $videoThumb = 'no-video.png';
        if ($request->hasFile('image')) {
            $imageName = 'news-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);
        }
        if ($request->hasFile('video')) {
            $video = 'video-'.time().uniqid().'.'.$request->video->getClientOriginalExtension();
            $request->video->move(public_path('img/news/video'), $video);
            $thumbnail_path= public_path('img/news/vthumbs');
            $videoUrl  = public_path('img/news/video/').$video;
            //$video_path       = $destination_path.'/'.$file_name;
            $thumbnail_image  = $video.".jpg";
            $thumbnail_status = VideoThumbnail::createThumbnail($videoUrl,$thumbnail_path,$thumbnail_image,2,$width = 640, $height = 480);
            //VideoThumbnail::createThumbnail($videoUrl, $storageUrl, $fileName, $second, $width = 640, $height = 480);
            //$abc = VideoThumbnail::createThumbnail(public_path('img/news/'), public_path('files/thumbs/'), 'movie.jpg', 2, 1920, 1080);
            if($thumbnail_status)
            {
                $videoThumb = $thumbnail_image;
              
            }
          
        }
            News::create([
                'title'         => $request->title,
                'slug'          => str_slug($request->title),
                'details'       => $request->details,
                'category_id'   => $request->category_id ?? 1,
                'image'         => $imageName,
                'video'         => $videoThumb,
                'status'        => $status,
                'featured'      => $featured
            ]);
    
        return redirect()->route('news.index')->with(['message' => 'News created successfully!']);
    }


    public function show(News $news)
    {
        //
    }


    public function edit(News $news)
    {   
        $data['menu'] = __('menu.Edit News');
        $data['sub_menu'] = 'Articles';
        $data['categories'] = Category::latest()->select('id','name')->where('status',1)->get();
        $data['news'] = News::findOrFail($news->id);     
        return view('admin.news.edit', $data);
    }

 
    public function update(Request $request, News $news)
    {
        $request->validate([
            'title'         => 'required|max:255',
            'details'       => 'required',
            'image'         => 'image|mimes:jpg,png,jpeg',
            'video'         => 'mimes:mp4,mov,ogg,webm|max:100000',
        ]);
        $status = true; //publish
        $featured = true; //on    
        $news = News::findOrFail($news->id);

        if ($request->hasFile('image')) {
            if(file_exists(public_path('img/news') . $news->image)){
                unlink(public_path('img/news') . $news->image);
            }

            $imageName = 'news-'.time().uniqid().'.'.$request->image->getClientOriginalExtension();
            $request->image->move(public_path('img/news'), $imageName);

        }else{
            $imageName = $news->image;
        }

        if ($request->hasFile('video')) {
            if(file_exists(public_path('img/news/video') . $news->video)){
                unlink(public_path('img/news/video') . $news->video);
            }

            $video = 'news-'.time().uniqid().'.'.$request->video->getClientOriginalExtension();
            $request->video->move(public_path('img/news/video'), $video);
            $thumbnail_path= public_path('img/news/vthumbs');
            $videoUrl  = public_path('img/news/video/').$video;

            $thumbnail_image  = $video.".jpg";
            $thumbnail_status = VideoThumbnail::createThumbnail($videoUrl,$thumbnail_path,$thumbnail_image,2,$width = 640, $height = 480);
        
            if($thumbnail_status)
            {
                $videoThumb = $thumbnail_image;
              
            }

        }else{
            $videoThumb = $news->video;
        }

        $news->update([
            'title'         => $request->title,
            'slug'          => str_slug($request->title),
            'details'       => $request->details,
            'category_id'   => $request->category_id ?? 1,
            'image'         => $imageName ?? 'no-thumbnail-post.jpg',
            'video'         => $videoThumb ?? 'no-video.png',
            'status'        => $status,
            'featured'      => $featured
        ]);

        return redirect()->route('news.index')->with(['message' => 'News updated successfully!']);
    }

 
    public function destroy(News $news)
    {
        $news = News::findOrFail($news->id);
        if($news->image !='no-thumbnail-post.jpg'){
            if(file_exists(public_path('img/news/') . $news->image)){
                unlink(public_path('img/news/') . $news->image);
            }
        }
        if($news->video !='no-video.png'){
            if(file_exists(public_path('img/news/vthumbs/') . $news->video)){
                unlink(public_path('img/news/vthumbs/') . $news->video);
            }
        }
        $videoname = str_replace('.jpg','',$news->video);
        if(file_exists(public_path('img/news/video/') . $videoname)){
            unlink(public_path('img/news/video/') . $videoname);
        }
        $news->delete();

        return back()->with(['message' => 'News deleted successfully!']);
    }
}

resources/views/admin/news/create.blade.php
@extends('layout.master')
@section('css')
<!-- include codemirror (codemirror.css, codemirror.js, xml.js, formatting.js) -->
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
<link rel="stylesheet" href="{{ asset('assets/iCheck/square/blue.css') }}">
<link rel="stylesheet" href="{{ asset('assets/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/summernote/summernote-bs4.css') }}">
@endsection
@section('content')
<section id="main-content">
          <section class="wrapper">
<!-- page start-->
<div class="row">
<div class="col-sm-12 overflow-auto">
<section class="card">

<header class="card-header">
    {{ $menu }}
<span class="tools pull-right">
<a href="javascript:;" class="fa fa-chevron-down"></a>
<a href="javascript:;" class="fa fa-times"></a>
</span>
</header>
<!-- card body -->
<div class="card-body">
</div>
<!-- end card body -->
<!-- card table -->
<div class="card-body overflow-auto">
       
            <form action="{{ route('news.store') }}" method="POST" enctype="multipart/form-data" role="form">
                @csrf
                <div class="row">
                <div class="col-md-8">
                    <div class="box-primary">
                        <div class="box-body">
                            <div class="form-group {!! $errors->has('title') ? 'error' : '' !!}">
                                <label for="newstitle">{{__('form.Title')}} *</label>
                                <input type="text" name="title" class="form-control" id="newstitle">
                                {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('details') ? 'error' : '' !!}">
                                <label>{{__('form.News Details')}} *</label>
                                <textarea class="textarea summernote" name="details" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                {!! $errors->first('details', '<p class="help-block">:message</p>') !!}
                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="box-primary">
                        <div class="box-body">
                            <div class="form-group">
                                <label>{{__('form.Categories')}}</label>
                                <select name="category_id" class="form-control select2" style="width: 100%;">
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group {!! $errors->has('image') ? 'error' : '' !!}">
                                <label for="newsimage">{{__('form.Featured Image')}}</label>
                                <input class="form-control"type="file" name="image" id="newsimage"> 
                                {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('video') ? 'error' : '' !!}">
                                <label for="newsimage">{{__('form.Featured Video')}}</label>
                                <input class="form-control"type="file" name="video" id="video">
                                {!! $errors->first('video', '<p class="help-block">:message</p>') !!}
                            </div>
                            {{--<div class="checkbox">
                                <label>
                                    <input type="checkbox" name="status"> Published
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="featured"> Featured
                                </label>
                            </div>--}}
                        </div>
                        <hr>
                        <div class="box-footer pull-right">
                            <button type="submit" class="btn btn-primary btn-flat">{{__('form.action.Create')}}</button>
                        </div>
                    </div>
                </div>
                </div>
            </form>

</div>
<!-- end card table -->
</section>
</div>
</div>
<!-- page end-->
    </section>
</section>
<!--main content end-->
@endsection
@section('js')
<!-- iCheck -->
<script src="{{ asset('assets/iCheck/icheck.min.js') }}"></script>
    <script src="{{ asset('assets/select2/js/select2.full.min.js') }}"></script>
    <script>
        $(function () {

            $('.select2').select2();

            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue'
            });
        });
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>
<script src="{{ asset('assets/summernote/summernote-bs4.js') }}"></script>
<script>
$('.summernote').summernote({
  height: 300,   //set editable area's height
  codemirror: { // codemirror options
    theme: 'monokai'
  }
});
</script>
@endsection

resources/views/admin/news/edit.blade.php
@extends('layout.master')
@section('css')
<!-- include codemirror (codemirror.css, codemirror.js, xml.js, formatting.js) -->
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.css">
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/theme/monokai.css">
<link rel="stylesheet" href="{{ asset('assets/iCheck/square/blue.css') }}">
<link rel="stylesheet" href="{{ asset('assets/select2/css/select2.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/summernote/summernote-bs4.css') }}">
@endsection
@section('content')
<section id="main-content">
          <section class="wrapper">
<!-- page start-->
<div class="row">
<div class="col-sm-12 overflow-auto">
<section class="card">

<header class="card-header">
    {{ $menu }}
<span class="tools pull-right">
<a href="javascript:;" class="fa fa-chevron-down"></a>
<a href="javascript:;" class="fa fa-times"></a>
</span>
</header>
<!-- card body -->
<div class="card-body">
</div>
<!-- end card body -->
<!-- card table -->
<div class="card-body overflow-auto">
       
            <form action="{{ route('news.update',[$news->id]) }}" method="POST" enctype="multipart/form-data" role="form">
                @csrf
                @method('PUT')
                <div class="row">
                <div class="col-md-8">
                    <div class="box-primary">
                        <div class="box-body">
                            <div class="form-group {!! $errors->has('title') ? 'error' : '' !!}">
                                <label for="newstitle">{{__('form.Title')}} *</label>
                                <input type="text" name="title" class="form-control" id="newstitle" value="{{$news->title}}">
                                {!! $errors->first('title', '<p class="help-block">:message</p>') !!}
                            </div>
                            <div class="form-group {!! $errors->has('details') ? 'error' : '' !!}">
                                <label>{{__('form.News Details')}} *</label>
                                <textarea class="textarea summernote" name="details" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                                {!! $news->details !!}
                                </textarea>
                                {!! $errors->first('details', '<p class="help-block">:message</p>') !!}
                            </div>

                        </div>
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="box-primary">
                        <div class="box-body">
                            <div class="form-group">
                                <label>{{__('form.Categories')}}</label>
                                <select name="category_id" class="form-control select2" id="#inputID" style="width: 100%;">
                                    @foreach($categories as $category)
                                        <option value="{{ $category->id }}" {{ ($news->id == $category->id) ? 'selected':''}}>{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group {!! $errors->has('image') ? 'error' : '' !!}">
                                <label for="newsimage">{{__('form.Featured Image')}}</label>
                                @if($news->image != '')
                                <div style="width:50%;margin:0 auto;padding:10px;">
                                <img class="img-thumbnail" src="{{ asset('img/news/'.$news->image) }}" alt="image">
                                </div>
                                @endif
                                <input class="form-control"type="file" name="image" id="newsimage">
                                {!! $errors->first('image', '<p class="help-block">:message</p>') !!}
        
                            </div>
                            <div class="form-group {!! $errors->has('video') ? 'error' : '' !!}">
                                <label for="newsimage">{{__('form.Featured Video')}}</label>
                                @if($news->video != '' || $news->video != null)
                                <div style="width:50%;margin:0 auto;padding:10px;">
                                <img class="img-thumbnail" src="{{ asset('img/news/vthumbs/'.$news->video) }}" alt="video">
                                </div>
                                @endif
                                <input class="form-control"type="file" name="video" id="video">
                                {!! $errors->first('video', '<p class="help-block">:message</p>') !!}
        
                            </div>
                            {{--<div class="checkbox">
                                <label>
                                    <input type="checkbox" name="status"> Published
                                </label>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="featured"> Featured
                                </label>
                            </div>--}}
                        </div>
                        <hr>
                        <div class="box-footer pull-right">
                            <button type="submit" class="btn btn-primary btn-flat">{{__('form.action.Update')}}</button>
                        </div>
                    </div>
                </div>
                </div>
            </form>

</div>
<!-- end card table -->
</section>
</div>
</div>
<!-- page end-->
    </section>
</section>
<!--main content end-->
@endsection
@section('js')
<!-- iCheck -->
<script src="{{ asset('assets/iCheck/icheck.min.js') }}"></script>
    <script src="{{ asset('assets/select2/js/select2.full.min.js') }}"></script>
    <script>
        $(function () {

            $('.select2').select2();
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue'
            });
        });
    </script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/codemirror.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/3.20.0/mode/xml/xml.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/codemirror/2.36.0/formatting.js"></script>
<script src="{{ asset('assets/summernote/summernote-bs4.js') }}"></script>
<script>
$('.summernote').summernote({
  height: 400,   //set editable area's height
  codemirror: { // codemirror options
    theme: 'monokai'
  }
});
</script>
@endsection

resources/views/admin/news/index.blade.php
@extends('layout.master')
@section('css')
@endsection
@section('content')
<section id="main-content">
          <section class="wrapper">
<!-- page start-->
<div class="row">
<div class="col-sm-12 overflow-auto">
<section class="card">

<header class="card-header">
    {{ $menu }}
<span class="tools pull-right">
<a  title="add"  href="{{ route('news.create') }}"><button type="button" class="btn btn-danger"> <i class="fa fa-pencil"></i>&nbsp;{{ __('table.action.create') }}</button></a>
<a href="javascript:;" class="fa fa-chevron-down"></a>
<a href="javascript:;" class="fa fa-times"></a>
</span>
</header>
<!-- card body -->
<div class="card-body">
</div>
<!-- end card body -->
<!-- card table -->
<div class="card-body overflow-auto">

    <div class="adv-table">
        <!-- Start table -->
        <!-- id="category-table" -->
        <table class="display table table-bordered table-striped" id="dynamic-table"> 
                            <thead>
                                <tr>
                                <th>{{ __('table.ID') }}</th>
                                    <th>{{ __('table.Title') }}</th>
                                    <th>{{ __('table.Category') }}</th>
                                    <th>{{ __('table.Image') }}</th>
                                    <th>{{ __('table.Video') }}</th>
                                    <th>{{ __('table.action.action') }}</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach($newslist as $news)
                                <tr class="gradeX">
                                    <td>{{ $news->id }}</td>
                                    <td>{{ $news->title }}</td>
                                    <td>{{ @$news->category->name }}</td>
                                    <!-- <td>{{ str_limit(strip_tags($news->details),300) }}</td> -->
                                    <td class="text-center">
                                        <img src="{{ asset('img/news/'.$news->image) }}" alt="{{ $news->image }}" height="60px">
                                    </td>
                                    <!-- <td>{{ $news->featured ? 'Featured' : '' }}</td> -->
                                    <td class="text-center">
                                        <img src="{{ asset('img/news/vthumbs/'.$news->video) }}" alt="{{ $news->video }}" height="60px">
                                    </td>
                                    <td>
                                        <div class="btn-group-horisontal text-center">
                                            <!-- <a href="" class="btn btn-primary btn-flat"><i class="fa fa-eye"></i></a> -->
                                            <a href="{{ route('news.edit',$news->id) }}" class="btn btn-warning btn-flat"><i class="fa fa-edit"></i></a>
                                            <a href="javascript:void(0)" class="btn btn-danger btn-flat"
                                                onclick="event.preventDefault();
                                                    document.getElementById('news-delete-form-{{$news->id}}').submit();">
                                                <i class="fa fa-trash-o"></i>
                                            </a>
                                            <form id="news-delete-form-{{$news->id}}" action="{{ route('news.destroy',$news->id) }}" method="POST" style="display: none;">
                                                @csrf 
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>

                            <tfoot>
                                <tr>
                                <th>{{ __('table.ID') }}</th>
                                    <th>{{ __('table.Title') }}</th>
                                    <th>{{ __('table.Category') }}</th>
                                    <th>{{ __('table.Image') }}</th>
                                    <th>{{ __('table.Video') }}</th>
                                    <th>{{ __('table.action.action') }}</th>
                                </tr>
                            </tfoot>
                        </table>
        <!-- End table -->
    </div>
</div>
<!-- end card table -->
</section>
</div>
</div>

<!-- page end-->
    </section>
</section>
<!--main content end-->
@endsection
@section('css')
@endsection